In [1]:
import pandas as pd
pd.set_option('display.max_columns', 50)

In [2]:
victimization_data = pd.read_csv('NCVS_PERSONAL_1993-2018/NCVS_PERSONAL_VICTIMIZATION_1993-2018.csv')
victimization_data

,year,weight,gender,race1r,hispanic,ethnic1r,ager,marital2,hincome,popsize,region,msa,direl,notify,weapon,weapcat,newcrime,newoff,seriousviolent,injury,treatment,vicservices,locationr
0,1993,2329.11326,1,1,2,1,5,2,88,NaN,-1,3,4,2,2,0,2,5,3,0,0.0,2.0,3
1,1993,2476.22023,2,1,2,1,3,1,2,NaN,-1,2,3,1,2,0,1,4,2,0,0.0,2.0,1
2,1993,2240.13354,1,1,2,1,7,5,1,NaN,-1,3,3,1,3,5,1,2,1,1,1.0,2.0,3
3,1993,3102.70342,1,1,2,1,5,2,2,NaN,-1,3,4,2,1,3,1,1,1,0,0.0,2.0,5
4,1993,2003.21519,1,1,2,1,1,1,3,NaN,-1,3,3,2,2,0,1,4,2,1,1.0,2.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57787,2018,4923.72993,2,1,1,4,2,1,7,1.0,3,2,6,2,3,5,2,5,3,0,0.0,2.0,4
57788,2018,2570.47232,1,2,2,2,7,2,6,1.0,3,2,5,2,2,0,1,4,2,0,0.0,2.0,1
57789,2018,2224.65724,2,1,2,1,6,5,7,1.0,1,2,1,1,2,0,1,4,2,1,1.0,1.0,1
57790,2018,1676.22725,1,2,2,2,8,3,5,1.0,3,3,3,1,1,2,1,3,1,1,1.0,1.0,1
57791,2018,1473.06034,1,1,1,4,3,1,2,4.0,3,1,5,1,1,1,1,2,1,0,0.0,2.0,3

In [3]:
victimization_data['locationr'].value_counts()

3    22593
1    18046
4     6969
5     5126
2     5058
Name: locationr, dtype: int64

In [4]:
victimization_data['gender'] = victimization_data['gender'].replace({1:'Male', 2:'Female'})
victimization_data['race1r'] = victimization_data['race1r'].replace({1:'White', 2:'Black', 3:'Other'})
victimization_data['hispanic'] = victimization_data['hispanic'].replace({1:'Hispanic', 2:'Non-Hispanic', 88:'Unknown'})
victimization_data['ethnic1r'] = victimization_data['ethnic1r'].replace({1:'Non-Hispanic White', 2:'Non-Hispanic Black', 
                                                                         3:'Non-Hispanic Other', 4:'Hispanic'})
victimization_data['ager'] = victimization_data['ager'].replace({1:'12 to 14', 2:'15 to 17', 3:'18 to 20', 4:'21 to 24', 
                                                                 5:'25 to 34', 6:'35 to 49', 7:'50 to 64', 8:'65 and older'})
victimization_data['marital2'] = victimization_data['marital2'].replace({1:'Never Married', 2:'Married', 3:'Widowed', 
                                                                         4:'Divorced', 5:'Separated', 88:'Unknown'})
victimization_data['hincome'] = victimization_data['hincome'].replace({1:'Less than $7,500', 2:'7,500 to 14,999', 
                                                                       3:'15,000 to 24,999', 4:'25,000 to 34,999', 
                                                                       5:'35,000 to 49,999', 6:'50,000 to 74,999', 
                                                                       7:'75,000 or more', 88:'Unknown'})
victimization_data['popsize'] = victimization_data['popsize'].replace({0.0:'Not a place', 1.0:'Under 100,000', 
                                                                       2.0:'100,000 to 249,999', 3.0:'250,000 to 499,999', 
                                                                       4.0:'500,000 to 999,999', 5.0:'1 million or more'})
victimization_data['region'] = victimization_data['region'].replace({1:'Northeast', 2:'Midwest', 3:'South', 
                                                                     4:'West', -1:'Unknown'})
victimization_data['msa'] = victimization_data['msa'].replace({1:'Urban', 2:'Suburban', 3:'Rural'})
victimization_data['direl'] = victimization_data['direl'].replace({1:'Intimates', 2:'Other Relatives',
                                                                   3:'Well-known/Casual Acquaintances', 4:'Stanger', 
                                                                   5:'Do not know relationship', 
                                                                   6:'Unknown number of offenders'})
victimization_data['notify'] = victimization_data['notify'].replace({1:'Yes', 2:'No', 3:'Unknown', 8:'Unknown'})
victimization_data['weapon'] = victimization_data['weapon'].replace({1:'Yes', 2:'No', 3:'Unknown'})
victimization_data['weapcat'] = victimization_data['weapcat'].replace({0:'No Weapon', 1:'Firearm', 2:'Knife', 3:'Other', 
                                                                       4:'Type Unknown', 5:'Unknown if offender had weapon'})
victimization_data['newcrime'] = victimization_data['newcrime'].replace({1:'Violent Victimization', 2:'Personal Theft/Larceny'})
victimization_data['newoff'] = victimization_data['newoff'].replace({1:'Rape/Sexual Assaul', 2:'Robbery', 
                                                                     3:'Aggravated Assault', 4:'Simple Assault', 
                                                                     5:'Personal Theft'})
victimization_data['seriousviolent'] = victimization_data['seriousviolent'].replace({1:'Violent Crime', 2:'Simple Assault', 
                                                                                     3:'Personal Theft', 4:'Property Crime'})
victimization_data['injury'] = victimization_data['injury'].replace({0:'Not Injured', 1:'Injured'})
victimization_data['treatment'] = victimization_data['treatment'].replace({0.0:'Not Injured', 1.0:'Not Treated', 2.0:'Treated'})
victimization_data['vicservices'] = victimization_data['vicservices'].replace({1.0:'Service Received', 
                                                                               2.0:'No Services Recieved'})
victimization_data['locationr'] = victimization_data['locationr'].replace({1:'Home', 2:'Friendly Location', 3:'Commercial', 
                                                                           4:'School', 5:'Other'})
victimization_data.head()

,year,weight,gender,race1r,hispanic,ethnic1r,ager,marital2,hincome,popsize,region,msa,direl,notify,weapon,weapcat,newcrime,newoff,seriousviolent,injury,treatment,vicservices,locationr
0,1993,2329.11326,Male,White,Non-Hispanic,Non-Hispanic White,25 to 34,Married,Unknown,NaN,Unknown,Rural,Stanger,No,No,No Weapon,Personal Theft/Larceny,Personal Theft,Personal Theft,Not Injured,Not Injured,No Services Recieved,Commercial
1,1993,2476.22023,Female,White,Non-Hispanic,Non-Hispanic White,18 to 20,Never Married,"7,500 to 14,999",NaN,Unknown,Suburban,Well-known/Casual Acquaintances,Yes,No,No Weapon,Violent Victimization,Simple Assault,Simple Assault,Not Injured,Not Injured,No Services Recieved,Home
2,1993,2240.13354,Male,White,Non-Hispanic,Non-Hispanic White,50 to 64,Separated,"Less than $7,500",NaN,Unknown,Rural,Well-known/Casual Acquaintances,Yes,Unknown,Unknown if offender had weapon,Violent Victimization,Robbery,Violent Crime,Injured,Not Treated,No Services Recieved,Commercial
3,1993,3102.70342,Male,White,Non-Hispanic,Non-Hispanic White,25 to 34,Married,"7,500 to 14,999",NaN,Unknown,Rural,Stanger,No,Yes,Other,Violent Victimization,Rape/Sexual Assaul,Violent Crime,Not Injured,Not Injured,No Services Recieved,Other
4,1993,2003.21519,Male,White,Non-Hispanic,Non-Hispanic White,12 to 14,Never Married,"15,000 to 24,999",NaN,Unknown,Rural,Well-known/Casual Acquaintances,No,No,No Weapon,Violent Victimization,Simple Assault,Simple Assault,Injured,Not Treated,No Services Recieved,Other

In [5]:
victimization_data = victimization_data.rename(columns={'year':'Year', 'weight':'Weight', 'gender':'Gender', 'race1r':'Race', 
                                   'hispanic':'Hispanic Origin', 'ethnic1r':'Race/Hispanic Origin', 'ager':'Age', 
                                   'marital2':'Marital Status', 'hincome':'Household Income', 'popsize':'Population Size', 
                                   'region':'Region', 'msa':'Location of Residence', 'direl':'Victim-offender Relationship', 
                                   'notify':'Police Report', 'weapon':'Presence of Weapon', 'weapcat':'Weapon Category', 
                                   'newcrime':'Aggregate Type of Crime', 'newoff':'Type of Crime', 
                                   'seriousviolent':'Violent Crime Excluding Simple Assault', 'injury':'Injury', 
                                   'treatment':'Treatment', 'vicservices':'Victim Services', 'locationr':'Location of Incident'})
victimization_data.head()

,Year,Weight,Gender,Race,Hispanic Origin,Race/Hispanic Origin,Age,Marital Status,Household Income,Population Size,Region,Location of Residence,Victim-offender Relationship,Police Report,Presence of Weapon,Weapon Category,Aggregate Type of Crime,Type of Crime,Violent Crime Excluding Simple Assault,Injury,Treatment,Victim Services,Location of Incident
0,1993,2329.11326,Male,White,Non-Hispanic,Non-Hispanic White,25 to 34,Married,Unknown,NaN,Unknown,Rural,Stanger,No,No,No Weapon,Personal Theft/Larceny,Personal Theft,Personal Theft,Not Injured,Not Injured,No Services Recieved,Commercial
1,1993,2476.22023,Female,White,Non-Hispanic,Non-Hispanic White,18 to 20,Never Married,"7,500 to 14,999",NaN,Unknown,Suburban,Well-known/Casual Acquaintances,Yes,No,No Weapon,Violent Victimization,Simple Assault,Simple Assault,Not Injured,Not Injured,No Services Recieved,Home
2,1993,2240.13354,Male,White,Non-Hispanic,Non-Hispanic White,50 to 64,Separated,"Less than $7,500",NaN,Unknown,Rural,Well-known/Casual Acquaintances,Yes,Unknown,Unknown if offender had weapon,Violent Victimization,Robbery,Violent Crime,Injured,Not Treated,No Services Recieved,Commercial
3,1993,3102.70342,Male,White,Non-Hispanic,Non-Hispanic White,25 to 34,Married,"7,500 to 14,999",NaN,Unknown,Rural,Stanger,No,Yes,Other,Violent Victimization,Rape/Sexual Assaul,Violent Crime,Not Injured,Not Injured,No Services Recieved,Other
4,1993,2003.21519,Male,White,Non-Hispanic,Non-Hispanic White,12 to 14,Never Married,"15,000 to 24,999",NaN,Unknown,Rural,Well-known/Casual Acquaintances,No,No,No Weapon,Violent Victimization,Simple Assault,Simple Assault,Injured,Not Treated,No Services Recieved,Other

In [8]:
victimization_data = victimization_data.dropna(how='any')
victimization_data.head()

,Year,Weight,Gender,Race,Hispanic Origin,Race/Hispanic Origin,Age,Marital Status,Household Income,Population Size,Region,Location of Residence,Victim-offender Relationship,Police Report,Presence of Weapon,Weapon Category,Aggregate Type of Crime,Type of Crime,Violent Crime Excluding Simple Assault,Injury,Treatment,Victim Services,Location of Incident
8861,1995,3463.13071,Male,White,Non-Hispanic,Non-Hispanic White,25 to 34,Never Married,"50,000 to 74,999","250,000 to 499,999",West,Urban,Stanger,Yes,No,No Weapon,Violent Victimization,Robbery,Violent Crime,Not Injured,Not Injured,No Services Recieved,Commercial
8862,1995,2497.65395,Female,White,Non-Hispanic,Non-Hispanic White,35 to 49,Married,"50,000 to 74,999","Under 100,000",Midwest,Suburban,Stanger,Yes,No,No Weapon,Violent Victimization,Simple Assault,Simple Assault,Not Injured,Not Injured,No Services Recieved,Commercial
8863,1995,2521.20834,Female,Black,Non-Hispanic,Non-Hispanic Black,25 to 34,Never Married,"50,000 to 74,999","Under 100,000",Midwest,Suburban,Stanger,Yes,Yes,Knife,Violent Victimization,Aggravated Assault,Violent Crime,Not Injured,Not Injured,No Services Recieved,Friendly Location
8864,1995,2023.97373,Male,White,Non-Hispanic,Non-Hispanic White,25 to 34,Married,"25,000 to 34,999",Not a place,South,Suburban,Stanger,Yes,No,No Weapon,Violent Victimization,Simple Assault,Simple Assault,Not Injured,Not Injured,No Services Recieved,Commercial
8865,1995,12143.84238,Male,White,Non-Hispanic,Non-Hispanic White,25 to 34,Married,"25,000 to 34,999",Not a place,South,Suburban,Stanger,Yes,No,No Weapon,Violent Victimization,Simple Assault,Simple Assault,Not Injured,Not Injured,No Services Recieved,Commercial

In [9]:
victimization_data.to_csv('clean_data/clean_victimization_data.csv', index=False)